### Load in NumPy

In [20]:
import numpy as np

### The Basics

In [21]:
a = np.array([1,2,3], dtype='int32')
a

array([1, 2, 3], dtype=int32)

In [22]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [23]:
# Get Dimension
a.ndim

1

In [24]:
b.ndim

2

In [25]:
# Get Shape
a.shape

(3,)

In [26]:
b.shape

(2, 3)

In [27]:
# Get Type
a.dtype

dtype('int32')

In [28]:
# Get Size
a.itemsize

4

In [31]:
b.itemsize

8

In [30]:
# Get total size
a.nbytes

12

### Accessing/Changing specific elements, rows, columns, etc

In [60]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]], dtype='int32')
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]], dtype=int32)

In [36]:
# Get a specific element [r,c]
a[1, 5]

np.int32(13)

In [37]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7], dtype=int32)

In [38]:
# Get a specific column
a[:, 2]

array([ 3, 10], dtype=int32)

In [39]:
# Getting a little more fancy [startindex:endingindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6], dtype=int32)

In [42]:
a[1,5] = 20
a

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [62]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [46]:
# Get specific element (work outside in)
b[0,1,1]

np.int32(4)

In [47]:
b[:,0,:]

array([[1, 2],
       [5, 6]], dtype=int32)

In [50]:
# replace
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]], dtype=int32)

### Initializing Different Types of Arrays

In [53]:
# All 0s matrix
np.zeros(5)

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [58]:
# Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [64]:
# Any other number (full_like)
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [66]:
# Random decimal numbers
np.random.rand(4,2,3)

array([[[0.69196739, 0.09580736, 0.46322089],
        [0.81718008, 0.37452748, 0.23001791]],

       [[0.96866905, 0.25453461, 0.48388994],
        [0.1251251 , 0.16108162, 0.31957461]],

       [[0.93063774, 0.927498  , 0.59606149],
        [0.15975987, 0.47787806, 0.98984898]],

       [[0.16507481, 0.69841219, 0.80333664],
        [0.94232243, 0.32477182, 0.20860623]]])

In [67]:
np.random.random_sample(a.shape)

array([[0.41215225, 0.80165254, 0.81895387, 0.3869362 , 0.92368927,
        0.51790917, 0.76316204],
       [0.05571222, 0.65915763, 0.39588619, 0.53866383, 0.53260878,
        0.85119045, 0.14925409]])

In [70]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 1,  2, -1],
       [ 3, -1,  4],
       [ 6,  4,  6]])

In [ ]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [87]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be Careful when copying arrays

In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(b)
print(a)

[100   2   3]
[1 2 3]


### Mathematics

In [91]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [92]:
a + 2

array([3, 4, 5, 6])

In [93]:
a - 2

array([-1,  0,  1,  2])

In [94]:
a * 2

array([2, 4, 6, 8])

In [95]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [96]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [97]:
a ** 2

array([ 1,  4,  9, 16])

In [98]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [100]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.nath.html)

### Linear Algebra

In [103]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [106]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...


### Statistics

In [107]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
np.min(stats, axis=0)

array([1, 2, 3])

In [ ]:
np.max(stats)

array([3, 6])

In [113]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [118]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before.shape)
print(before)

after = before.reshape((8,1))
print(after)

after = before.reshape((2,2,2))
print(after)

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [119]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [121]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

##### Load Data from File

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
# filedata.astype('int32')    # Makes a copy of the data
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

##### Boolean Masking and Advanced Indexing

In [128]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [129]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [132]:
# You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [135]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [136]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [138]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [139]:
~((filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [187]:
arr = np.arange(1, 31)
print(arr)

arr = arr.reshape((6,5))
print(arr)

arr[2:4, 0:2]

arr[[0,1,2,3], [1,2,3,4]]

arr[[0,4,5], 3:]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


array([[ 4,  5],
       [24, 25],
       [29, 30]])